steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/pet-grooming-api:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/pet-grooming-api:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'pet-grooming-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/pet-grooming-api:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - 'urania-418623:us-central1:pet-grooming-db'
      - '--set-env-vars'
      - 'ENVIRONMENT=production,JWT_SECRET=production-jwt-secret-key,DATABASE_URL=postgresql://petuser:petgrooming_password_2025@/petgrooming?host=/cloudsql/urania-418623:us-central1:pet-grooming-db'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'

images:
  - 'gcr.io/$PROJECT_ID/pet-grooming-api:latest'