name: Build iOS App

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'mobile/**'
      - '.github/workflows/ios-build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'mobile/**'
      - '.github/workflows/ios-build.yml'
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true

    - name: Get Flutter dependencies
      working-directory: mobile
      run: flutter pub get

    - name: Run Flutter tests
      working-directory: mobile
      run: flutter test

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Install CocoaPods
      run: sudo gem install cocoapods

    - name: Install iOS dependencies
      working-directory: mobile/ios
      run: pod install

    - name: Import Development Certificate
      uses: Apple-Actions/import-codesign-certs@v2
      with:
        p12-file-base64: ${{ secrets.IOS_DEV_SIGNING_KEY }}
        p12-password: ${{ secrets.IOS_DEV_SIGNING_KEY_PASSWORD }}

    - name: Install Development Provisioning Profile
      run: |
        # Create provisioning profile directory
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        # Decode and install provisioning profile from secret
        echo "${{ secrets.IOS_DEV_PROVISIONING_PROFILE }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/development.mobileprovision

    - name: Configure Export Options
      working-directory: mobile/ios
      run: |
        # Replace placeholder values in ExportOptionsDevelopment.plist
        sed -i '' "s/YOUR_TEAM_ID/${{ secrets.APPLE_TEAM_ID }}/g" ExportOptionsDevelopment.plist
        sed -i '' "s/YOUR_DEVELOPMENT_PROVISIONING_PROFILE_NAME/${{ secrets.IOS_DEV_PROVISIONING_PROFILE_NAME }}/g" ExportOptionsDevelopment.plist

    - name: Build iOS Development IPA
      working-directory: mobile
      run: |
        # Build iOS app with development signing
        flutter build ios --release --no-codesign

        # Create archive with development team
        xcodebuild -workspace ios/Runner.xcworkspace \
          -scheme Runner \
          -configuration Release \
          -archivePath build/ios/Runner.xcarchive \
          DEVELOPMENT_TEAM=${{ secrets.APPLE_TEAM_ID }} \
          archive

        # Export development IPA
        xcodebuild -exportArchive \
          -archivePath build/ios/Runner.xcarchive \
          -exportPath build/ios/ipa \
          -exportOptionsPlist ios/ExportOptionsDevelopment.plist

    - name: Upload Development IPA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: pet-grooming-ios-dev-${{ github.sha }}
        path: mobile/build/ios/ipa/*.ipa
        retention-days: 30