name: Build iOS App

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'mobile/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'mobile/**'
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        cache: true

    - name: Get Flutter dependencies
      working-directory: mobile
      run: flutter pub get

    - name: Run Flutter tests
      working-directory: mobile
      run: flutter test

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Install CocoaPods
      run: sudo gem install cocoapods

    - name: Install iOS dependencies
      working-directory: mobile/ios
      run: pod install

    - name: Import Code-Signing Certificates
      if: github.event_name != 'pull_request'
      uses: Apple-Actions/import-codesign-certs@v2
      with:
        p12-file-base64: ${{ secrets.IOS_DIST_SIGNING_KEY }}
        p12-password: ${{ secrets.IOS_DIST_SIGNING_KEY_PASSWORD }}

    - name: Install Provisioning Profile
      if: github.event_name != 'pull_request'
      uses: Apple-Actions/download-provisioning-profiles@v1
      with:
        bundle-id: com.petgrooming.app
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

    - name: Build iOS (Debug - for PR)
      if: github.event_name == 'pull_request'
      working-directory: mobile
      run: |
        flutter build ios --debug --no-codesign

    - name: Build iOS (Release)
      if: github.event_name != 'pull_request'
      working-directory: mobile
      run: |
        flutter build ios --release

    - name: Build IPA
      if: github.event_name != 'pull_request'
      working-directory: mobile
      run: |
        mkdir -p build/ios/ipa
        xcodebuild -workspace ios/Runner.xcworkspace \
          -scheme Runner \
          -sdk iphoneos \
          -configuration Release \
          -archivePath build/ios/Runner.xcarchive \
          archive
        xcodebuild -exportArchive \
          -archivePath build/ios/Runner.xcarchive \
          -exportOptionsPlist ios/ExportOptions.plist \
          -exportPath build/ios/ipa

    - name: Upload IPA Artifact
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: pet-grooming-ios-${{ github.sha }}
        path: mobile/build/ios/ipa/*.ipa
        retention-days: 30

    - name: Upload to TestFlight (Optional)
      if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
      working-directory: mobile
      run: |
        xcrun altool --upload-app \
          --type ios \
          --file build/ios/ipa/*.ipa \
          --username ${{ secrets.APPLE_ID }} \
          --password ${{ secrets.APPLE_APP_PASSWORD }}