name: Reveal Secret
on: workflow_dispatch

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Output secret
        run: |
          echo "${{ secrets.IOS_DEV_SIGNING_KEY_PASSWORD }}" | base64
