name: Reveal Secret
on: workflow_dispatch

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Save cert to file
        run: |
          echo "${{ secrets.IOS_DEV_SIGNING_KEY }}" > cert_base64.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cert
          path: cert_base64.txt
